### ISSUE TITLE
xception in thread "ForkJoinPool-2-worker-27" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#25]
what is this?

**Comment by SchurchLab** [comment]
Exception in thread "ForkJoinPool-2-worker-2" java.lang.OutOfMemoryError: Java heap space
> 	at ij.process.FloatProcessor.<init>(FloatProcessor.java:37)
> 	at mpicbg.imglib.container.imageplus.FloatImagePlus.<init>(FloatImagePlus.java:78)
> 	at mpicbg.imglib.container.imageplus.ImagePlusContainerFactory.createFloatInstance(ImagePlusContainerFactory.java:100)
> 	at mpicbg.imglib.type.numeric.real.FloatType.createSuitableDirectAccessContainer(FloatType.java:83)
> 	at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:69)
> 	at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:55)
> 	at mpicbg.imglib.image.Image.<init>(Image.java:113)
> 	at mpicbg.imglib.image.Image.<init>(Image.java:136)
> 	at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:69)
> 	at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:72)
> 	at mpicbg.imglib.algorithm.fft.FFTFunctions.computeInverseFFT(FFTFunctions.java:80)
> 	at mpicbg.imglib.algorithm.fft.InverseFourierTransform.process(InverseFourierTransform.java:130)
> 	at mpicbg.imglib.algorithm.fft.PhaseCorrelation.process(PhaseCorrelation.java:196)
> 	at com.akoya.codex.upload.driffta.Driftcomp.computeShift(Driftcomp.java:75)
> 	at com.akoya.codex.upload.driffta.Driftcomp.lambda$compensateDrift$0(Driftcomp.java:52)
> 	at com.akoya.codex.upload.driffta.Driftcomp$$Lambda$3/1175259735.run(Unknown Source)
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Exception in thread "ForkJoinPool-2-worker-22" java.lang.OutOfMemoryError: Java heap space
> 	at ij.process.FloatProcessor.<init>(FloatProcessor.java:37)
> 	at mpicbg.imglib.container.imageplus.FloatImagePlus.<init>(FloatImagePlus.java:78)
> 	at mpicbg.imglib.container.imageplus.ImagePlusContainerFactory.createFloatInstance(ImagePlusContainerFactory.java:100)
> 	at mpicbg.imglib.type.numeric.real.FloatType.createSuitableDirectAccessContainer(FloatType.java:83)
> 	at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:69)
> 	at mpicbg.imglib.container.DirectAccessContainerFactory.createContainer(DirectAccessContainerFactory.java:55)
> 	at mpicbg.imglib.image.Image.<init>(Image.java:113)
> 	at mpicbg.imglib.image.Image.<init>(Image.java:136)
> 	at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:69)
> 	at mpicbg.imglib.image.ImageFactory.createImage(ImageFactory.java:72)
> 	at mpicbg.imglib.algorithm.fft.FFTFunctions.computeInverseFFT(FFTFunctions.java:80)
> 	at mpicbg.imglib.algorithm.fft.InverseFourierTransform.process(InverseFourierTransform.java:130)
> 	at mpicbg.imglib.algorithm.fft.PhaseCorrelation.process(PhaseCorrelation.java:196)
> 	at com.akoya.codex.upload.driffta.Driftcomp.computeShift(Driftcomp.java:75)
> 	at com.akoya.codex.upload.driffta.Driftcomp.lambda$compensateDrift$0(Driftcomp.java:52)
> 	at com.akoya.codex.upload.driffta.Driftcomp$$Lambda$3/1175259735.run(Unknown Source)
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source)
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

**Comment by vishal266** [comment]
This issue has been resolved
