### ISSUE TITLE
Cannot intialize the experiment that doesn't contain Experiment.json file

### ISSUE THREAD

**Issue by nsamusik** [nolanlab/CODEX#3]
Seems like it's happening again

**Comment by nsamusik** [comment]
Sorry - the issue is actually different. It actually seems that whenever you open a folder and there is an error, instead of showing what the error actually is, the program simply pops up a dialog box that shows the path to the Experiment.json file. Could you change it so that it shows the actual error message?

**Comment by vishal266** [comment]
This issue has been fixed in the latest github revision. The release has not happened yet.

**Comment by vishal266** [comment]
The fix is available in the latest release.
