### ISSUE TITLE
Segmentation masks for 30-antibody spleen dataset

### ISSUE THREAD

**Issue by gokceneraslan** [nolanlab/CODEX#31]
Hi there, 

First of all, thanks for the amazing work, really great paper! Sorry for asking here, but are the segmentation masks for 30-antibody spleen dataset publicly available?

**Comment by vishal266** [comment]
@nsamusik ,

Can you please look at this?

**Comment by nsamusik** [comment]
Hi gokceneraslan, 

Unfortunately we don't have them available. The FCS files contain cell X,Y,Z and size, if that's helpful

Nikolay
