### ISSUE TITLE
Segmentation - Creating a map to calculate X and Y offsets... > null

### ISSUE THREAD

**Issue by eric-czech** [nolanlab/CODEX#33]
Hey Vishal,

We are getting a null error at the end of segmentation (image attached), regardless of the version of CODEX, 1.2.5 or 1.3. There is a maxRAM of 64. Any help is much appreciated. 

Separate question, can you run Segmentation without deconvolution or an alternative deconvolution package?

Thank you,
Ash (on behalf of Eric)

![seg error 1 3](https://user-images.githubusercontent.com/6130352/38143859-377b449e-33f7-11e8-806e-6a6bdd40c993.png)

**Comment by vishal266** [comment]
Hello @eric-czech ,

Did you get any error/log on the command window while executing this? 

I am not sure about the second question, @nsamusik will be able to help you better with that.

Thanks,
Vishal

**Comment by eric-czech** [comment]
Nope, nothing else to go on unfortunately.

**Comment by vishal266** [comment]
@eric-czech ,

Can you try running it from command line? 
Also, please make sure that the folder has tileMap.txt. 
Can you send the screenshot of the folder structure that was used as input for segmentation?

**Comment by eric-czech** [comment]
Aha yea that was it.  Thanks @vishal266 !

**Comment by vishal266** [comment]
No problem!
