### ISSUE TITLE
Segmentation issues 

### ISSUE THREAD

**Issue by phillidj** [nolanlab/CODEX#34]
When we included a membrane stain (Na-K-ATPase), the segmentation was worse. 

1. For instance, when we added Na-K-ATPase, the nuclear channel was blank. This seemed to resolve when we selected the nuclear and membrane stains from the same cycle.  
2. When including Na-K-ATPase, the segmentation missed 30% of the cells. 
3. When including Na-K-ATPase, the image saturation was worse. 

Thanks!

**Comment by nsamusik** [comment]
Thanks! Can you give me a sample TIFF stack image and the segmentation config files that you used?

**Comment by vishal266** [comment]
Closing as it is outdated.
