### ISSUE TITLE
unable to upload data with 1x1 tiles

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#36]
Vishal,

Graham and I wanted to upload data from 9 regions, each 1x1 in size (only one tile). It doesn't work - it's not possible to start the upload.

Could you please look into this?

Thanks,
Christian

**Comment by vishal266** [comment]
Hi Christian,

Do you have this data on the left CODEX machine? Can I take a look at it? Does it display any error?

Thanks,
Vishal

**Comment by SchurchLab** [comment]
Hi Vishal

It’s in Grahams disk on the left computer. I’m not sure if Akoya people are using it right now.

You can have a look if you want.

Thanks
Christian

Am 19.04.2018 um 10:30 schrieb vishal266 <notifications@github.com<mailto:notifications@github.com>>:


Hi Christian,

Do you have this data on the left CODEX machine? Can I take a look at it? Does it display any error?

Thanks,
Vishal

**Comment by SchurchLab** [comment]
Hi Vishal,

Were you able to take a look at this?  Any ideas?


Thanks,

Graham

________________________________

**Comment by vishal266** [comment]
Hi Graham,

Is any one using that machine right now? I want to make sure that no one is using it before I can kick them out.

**Comment by SchurchLab** [comment]
Hi vishal

Yes you can use it now.

Christian

Am 19.04.2018 um 13:34 schrieb vishal266 <notifications@github.com<mailto:notifications@github.com>>:


Hi Graham,

Is any one using that machine right now? I want to make sure that no one is using it before I can kick them out.

**Comment by vishal266** [comment]
This issue has been fixed. Supports different folders in exp folder.
