### ISSUE TITLE
Installer changes request

### ISSUE THREAD

**Issue by nsamusik** [nolanlab/CODEX#4]
1) Change CODEXToolkit shortcut name into CODEXuploader
2) Group the icons in the Start menu into a single 'CODEXToolkit' folder (right now they are loose)

**Comment by vishal266** [comment]
Sure, I will make these changes

**Comment by vishal266** [comment]
These changes have been done and the setup files have been updated. The release has not happened yet.

**Comment by vishal266** [comment]
Now available in latest release.
