### ISSUE TITLE
segmenter fails to create FCS file

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#42]
Hi Vishal

I segmented on the left computer and it is done - except that it failed to make the FCS file. I tried twice already. On Monday it still worked.

Is it possible that it has something to do with the H&E staining ?

Could you please look into this. It is still open on the left computer.

Thanks!
Christian

**Comment by vishal266** [comment]
Hi Christian,

Can you let me know the experiment name and give the directory in which data is present so that I can have a look at it?

Thanks,
Vishal

**Comment by vishal266** [comment]
Closing as it is outdated(possibly fixed)
