### ISSUE TITLE
Tile processing failed 3 times 

### ISSUE THREAD

**Issue by ashstatic** [nolanlab/CODEX#43]
Hey Vishal,

Can you please look at what is happening? The v1.3.3 processor is failing. 

I attached the error log from the user, the channel, and exp time, and the experiment.json which I had to make a 'text' file to load. 

The end error is:
> java.lang.NullPointerException
> 	at com.akoya.codex.upload.driffta.Driffta.getHighestExpCycForEveryChannel(Driffta.java:692)
> 	at com.akoya.codex.upload.driffta.Driffta.backgroundSubtraction(Driffta.java:734)
> 	at com.akoya.codex.upload.driffta.Driffta.main(Driffta.java:495)
> Process done
> Driffta done
> Tile processing failed 3 times in a row: reg001_X01_Y01.tif

Thank you,
Ash

[channelNames.txt](https://github.com/nolanlab/CODEX/files/2089795/channelNames.txt)

[Experiment.json.txt](https://github.com/nolanlab/CODEX/files/2089799/Experiment.json.txt)
[exposure_times (4).txt](https://github.com/nolanlab/CODEX/files/2089796/exposure_times.4.txt)
[processing lines.docx](https://github.com/nolanlab/CODEX/files/2089797/processing.lines.docx)

**Comment by vishal266** [comment]
Hi Ash,

There is something wrong with the exposure_times.txt file. First is its name, kindly remove (4) from the file name. Also, the content has to be tab space separated and should contain exposure times in fractions. Please check the attached exposure_times.txt file for reference. 

Hope this helps.

**Comment by vishal266** [comment]
[exposure_times.txt](https://github.com/nolanlab/CODEX/files/2095348/exposure_times.txt)

**Comment by vishal266** [comment]
These are the list of exposure_times in fraction that is currently supported: 

expVsMs.put("skip", (double)0);
        expVsMs.put("1/7500s", (double)1000 * 1/7500);
        expVsMs.put("1/5500s", (double)1000 * 1/5500);
        expVsMs.put("1/4500s", (double)1000 * 1/4500);
        expVsMs.put("1/4000s", (double)1000 * 1/4000);
        expVsMs.put("1/3200s", (double)1000 * 1/3200);
        expVsMs.put("1/2800s", (double)1000 * 1/2800);
        expVsMs.put("1/2500s", (double)1000 * 1/2500);
        expVsMs.put("1/2250s", (double)1000 * 1/2250);
        expVsMs.put("1/2000s", (double)1000 * 1/2000);
        expVsMs.put("1/1500s", (double)1000 * 1/1500);
        expVsMs.put("1/1300s", (double)1000 * 1/1300);
        expVsMs.put("1/1100s", (double)1000 * 1/1100);
        expVsMs.put("1/1000s", (double)1000 * 1/1000);
        expVsMs.put("1/800s", (double)1000 * 1/800);
        expVsMs.put("1/700s", (double)1000 * 1/700);
        expVsMs.put("1/600s", (double)1000 * 1/600);
        expVsMs.put("1/500s", (double)1000 * 1/500);
        expVsMs.put("1/400s", (double)1000 * 1/400);
        expVsMs.put("1/350s", (double)1000 * 1/350);
        expVsMs.put("1/300s", (double)1000 * 1/300);
        expVsMs.put("1/250s", (double)1000 * 1/250);
        expVsMs.put("1/200s", (double)1000 * 1/200);
        expVsMs.put("1/175s", (double)1000 * 1/175);
        expVsMs.put("1/150s", (double)1000 * 1/150);
        expVsMs.put("1/120s", (double)1000 * 1/120);
        expVsMs.put("1/100s", (double)1000 * 1/100);
        expVsMs.put("1/80s", (double)1000 * 1/80);
        expVsMs.put("1/70s", (double)1000 * 1/70);
        expVsMs.put("1/60s", (double)1000 * 1/60);
        expVsMs.put("1/50s", (double)1000 * 1/50);
        expVsMs.put("1/40s", (double)1000 * 1/40);
        expVsMs.put("1/35s", (double)1000 * 1/35);
        expVsMs.put("1/30s", (double)1000 * 1/30);
        expVsMs.put("1/25s", (double)1000 * 1/25);
        expVsMs.put("1/20s", (double)1000 * 1/20);
        expVsMs.put("1/15s", (double)1000 * 1/15);
        expVsMs.put("1/12s", (double)1000 * 1/12);
        expVsMs.put("1/10s", (double)1000 * 1/10);
        expVsMs.put("1/8.5s", 1000 * 1/8.5);
        expVsMs.put("1/7.5s", 1000 * 1/7.5);
        expVsMs.put("1/6s", (double)1000 * 1/6);
        expVsMs.put("1/5s", (double)1000 * 1/4);
        expVsMs.put("1/4s", (double)1000 * 1/4);
        expVsMs.put("1/3.5s", 1000 * 1/3.5);
        expVsMs.put("1/3s", (double)1000 * 1/3);
        expVsMs.put("1/2.5s", 1000 * 1/2.50);
        expVsMs.put("1/2.3s", 1000 * 1/2.3);
        expVsMs.put("1/2s", (double)1000 * 1/2);
        expVsMs.put("1/1.7s", 1000 * 1/1.7);
        expVsMs.put("1/1.5s", 1000 * 1/1.5);
        expVsMs.put("1/1.2s", 1000 * 1/1.2);
        expVsMs.put("1s", (double)1000 * 1);
        expVsMs.put("1.2s", 1000 * 1.2);
        expVsMs.put("1.5s", 1000 * 1.5);
        expVsMs.put("2s", (double)1000 * 2);
        expVsMs.put("2.5s", (double)1000 * 2.5);
        expVsMs.put("3s", (double)1000 * 3);
        expVsMs.put("3.5s", 1000 * 3.5);
        expVsMs.put("4s", (double)1000 * 4);
        expVsMs.put("4.5s", (double)1000 * 4.5);
        expVsMs.put("5s", (double)1000 * 5);

**Comment by ashstatic** [comment]
Thanks Vishal. Quick follow-up. For users of Zeiss and Leica that don't have values in fractions, do they now have to switch over to fractions from whole numbers in the exposure times file?

**Comment by vishal266** [comment]
Umm, I think you can try it out. But it would be better to have the values from the above mentioned values. If its not in fraction, may be like 1.5s, 2.5s, etc. But it has to be in the pair mentioned in the previous comment. Hope this helps!
