### ISSUE TITLE
Stitching removing too much from Zeiss data

### ISSUE THREAD

**Issue by ashstatic** [nolanlab/CODEX#44]
Hey Vishal and Nikolay,

These are the files I shared the other week. I did confirm with the Zeiss Engineer who was on site, that the overlap being taken for this Zeiss is 10%.

When using a 10% overlap in V1.3.3, too much is removed. It appears to be ~6-7% that should be removed, that is still an approximation. 

Thank you,
Ash

**Comment by vishal266** [comment]
Hi @ashstatic ,

I am closing this issue here as it is being fixed by Won-Mean
