### ISSUE TITLE
use membrane channel segmentation

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#47]
Hi Vishal

when I want to segment using membrane channel, it always says "false" in the config.txt file, even though I put numbers in channel and cycle. Could you please have a look, I think it doesn't work properly.

Thanks!
Christian

**Comment by vishal266** [comment]
Hi Christian, 

Isn't the membrane channel a number value?? It can't be false.

**Comment by vishal266** [comment]
Closing as it is outdated.
