### ISSUE TITLE
Segmentation cannot create FCS file when last frame/cycle is H&E

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#48]
problem has been described and shown to Vishal

**Comment by vishal266** [comment]
This could probably happen if there is an error in the processed data that has an error with respect to the H&E cycle. In other words, if there are 13 cycles and HandE cycle, processed data should have automatically done it for 14 cyles, if it didn't, then there is an error and if the segmentation is run for this data, fcs files wont be created.

**Comment by SchurchLab** [comment]
yes, correct! if everything is fine, H&E does not affect the segmentation. I tested it and it works. Thanks man!

**Comment by vishal266** [comment]
Cool!
