### ISSUE TITLE
Index out of bounds exception - Background subtraction with H&E

### ISSUE THREAD

**Issue by SchurchLab** [nolanlab/CODEX#50]
In trying to do background subtraction, the following statement appears:

![image](https://user-images.githubusercontent.com/34288306/44859002-0ce7fe80-ac28-11e8-8f11-8666840f24b4.png)

**Comment by SchurchLab** [comment]
It is related to H&E cycle. the H&E cycle should not be considered for the background subtraction. if possible, please update the algorithm so that H&E is incorporated, but ignored for the background subtraction.

thanks!!

**Comment by vishal266** [comment]
This issue has been fixed
