### ISSUE TITLE
Segmentation - Out of Memory Error

### ISSUE THREAD

**Issue by sherman5** [nolanlab/CODEX#59]
I'm trying to run the cell segmentation program on a processed set of images, but I'm running into the following error:

```
> >>>>>>>>>>>>>>>>>>>>>>>>>>>
> <Out of memory>
> <All available memory (247MB) has been>
> <used. To make more available, use the>
> <Edit>Options>Memory & Threads command.>
> >>>>>>>>>>>>>>>>>>>>>>>>>>>
```

I have 16GB of memory available so the 247MB value doesn't make sense to me. When I google this error it takes me to ImageJ support pages, so I think this is a problem with the configuration of ImageJ, but I have no idea how to change that configuration through the segmentation program. Are there command line arguments I should be using to control the available memory? I'm calling the segmentation program as follows:

`java -cp CODEX-1.0-jar-with-dependencies.jar org.nolanlab.codex.segm.SegmMain`

I then select `CODEX_Analysis/Processed/bestFocus` as the source folder, my directory layout looks like:

```
CODEX_Analysis/
└── Processed
    ├── bestFocus
    │   ├── config.txt
    │   ├── reg001_X01_Y01_Z09.tif
    │   ├── reg002_X01_Y01_Z10.tif
    │   ├── reg003_X01_Y01_Z12.tif
    │   └── etc....
    ├── channelNames.txt
    ├── Experiment.json
    └── tileMap.txt

```

Here's a screenshot of the GUI window that pops up. I use the parameters
in the screenshot and then hit "start", that's when I see the error.

![CODEX_Segm](https://user-images.githubusercontent.com/8828115/55816854-425ba100-5ac1-11e9-88b3-8c1d227577d9.png)

Any help is greatly appreciated,
Tom

**Comment by vishal266** [comment]
Hello @sherman5 ,

1. Can you let me know your system configuration (RAM, GPU, CPU) and what version of java(32-bit or 64-bit) you are using? 
2. Also, you shouldn't select the bestFocus folder. You should select the processed folder as the input for segmentation, otherwise it will fail.

**Comment by sherman5** [comment]
CPU: Intel i7-8650U CPU
RAM: 16 GB
GPU: Intel Integrated Graphics
Java 32-bit

Thanks for clarifying that, I'm a little lost in general on the proper way to run the program. The `java -cp CODEX-1.0-jar-with-dependencies.jar org.nolanlab.codex.segm.SegmMain` command seems to be working, but I'd like to be running it correctly.

Also, I've been able to get around the memory issue for now by passing `-Xms1024m` but I can't specify a much larger heap without getting an error.

**Comment by vishal266** [comment]
Please install Java 64 bit. It wont work as expected without that.

**Comment by sherman5** [comment]
The combination of 64-bit Java and using -Xms seems to have fixed it, thank you
